---
# - name: get Rabbimq
#   get_url: 
#       url:  "{{ item }}"
#       dest: /root/
#   loop:
#    - https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.8.16/rabbitmq-server-3.8.16-1.el7.noarch.rpm
#    - http://mirror.centos.org/centos/7/os/x86_64/Packages/socat-1.7.3.2-2.el7.x86_64.rpm
#    - https://github.com/rabbitmq/erlang-rpm/releases/download/v23.2.6/erlang-23.2.6-1.el7.x86_64.rpm
- name: copy packages
  copy: 
    src: packages
    dest: /root/
- name: install rabbitmq
  yum:
    name: /root/packages/{{ item }}
    state: present 
  loop: 
    - socat-1.7.3.2-2.el7.x86_64.rpm
    - erlang-23.2.6-1.el7.x86_64.rpm
    - rabbitmq-server-3.8.16-1.el7.noarch.rpm
  
- name: stop service
  service:
      name: rabbitmq-server
      state: stopped
- name: use erlang string
  copy:
      src: .erlang.cookie
      dest: /var/lib/rabbitmq/.erlang.cookie
      owner: rabbitmq
      group: rabbitmq
      mode: '400'