---
- name: install epel
  yum:
    name:
        - epel-release
        - yum-utils
        - https://rpms.remirepo.net/enterprise/remi-release-7.rpm
        - socat
    state: latest
    # enablerepo: "remi"
  become: True
  #when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'
# - name: install erlang
#   yum:
#     name:
#         - erlang
#     state: latest
#   become: True
