---


- name: open ports
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
      - 4369/tcp
      - 5672/tcp
      - 15672/tcp
      - 25672/tcp
- name: restart firewall
  systemd:
    name: firewalld
    state: reloaded
    